[package]
name = "layer-shell-pipewire"
version = "0.1.0"
edition = "2021"

[dependencies]
pipewire = "0.8"
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
