use crate::widgets::widget;

widget!(TopBarWindow, gtk4::Window);
widget!(WorkspacesWidgetButton1, gtk4::Button);
widget!(WorkspacesWidgetButton2, gtk4::Button);
widget!(WorkspacesWidgetButton3, gtk4::Button);
widget!(WorkspacesWidgetButton4, gtk4::Button);
widget!(WorkspacesWidgetButton5, gtk4::Button);
widget!(WorkspacesWidgetButton6, gtk4::Button);
widget!(WorkspacesWidgetButton7, gtk4::Button);
widget!(WorkspacesWidgetButton8, gtk4::Button);
widget!(WorkspacesWidgetButton9, gtk4::Button);
widget!(WorkspacesWidgetButton10, gtk4::Button);
widget!(HtopWidget, gtk4::Button);
widget!(WeatherWidget, gtk4::Button);
widget!(WeatherWidgetLabel, gtk4::Label);
widget!(LanguageWidgetLabel, gtk4::Label);
widget!(SoundWidgetImage, gtk4::Image);
widget!(SoundWidgetScale, gtk4::Scale);
widget!(CPUWidgetLabel1, gtk4::Label);
widget!(CPUWidgetLabel2, gtk4::Label);
widget!(CPUWidgetLabel3, gtk4::Label);
widget!(CPUWidgetLabel4, gtk4::Label);
widget!(CPUWidgetLabel5, gtk4::Label);
widget!(CPUWidgetLabel6, gtk4::Label);
widget!(CPUWidgetLabel7, gtk4::Label);
widget!(CPUWidgetLabel8, gtk4::Label);
widget!(CPUWidgetLabel9, gtk4::Label);
widget!(CPUWidgetLabel10, gtk4::Label);
widget!(CPUWidgetLabel11, gtk4::Label);
widget!(CPUWidgetLabel12, gtk4::Label);
widget!(RAMWidget, gtk4::Button);
widget!(RAMWidgetLabel, gtk4::Label);
widget!(NetworkWidget, gtk4::Button);
widget!(NetworkWidgetLabel, gtk4::Label);
widget!(ClockWidgetLabel, gtk4::Label);
widget!(PowerWidget, gtk4::Button);
widget!(LogoutScreenWindow, gtk4::Window);
widget!(LogoutScreenLockButton, gtk4::Button);
widget!(LogoutScreenRebootButton, gtk4::Button);
widget!(LogoutScreenShutdownButton, gtk4::Button);
widget!(LogoutScreenLogoutButton, gtk4::Button);
widget!(NetworksWindow, gtk4::Window);
widget!(NetworkRow1, gtk4::CenterBox);
widget!(NetworkRow2, gtk4::CenterBox);
widget!(NetworkRow3, gtk4::CenterBox);
widget!(NetworkRow4, gtk4::CenterBox);
widget!(NetworkRow5, gtk4::CenterBox);
widget!(NetworkSettingsRow, gtk4::CenterBox);
widget!(NetworkExitRow, gtk4::CenterBox);
widget!(LauncherWindow, gtk4::Window);
widget!(LauncherEntry, gtk4::SearchEntry);
widget!(LauncherRow1, gtk4::Box);
widget!(LauncherRow1Image, gtk4::Image);
widget!(LauncherRow1Label, gtk4::Label);
widget!(LauncherRow2, gtk4::Box);
widget!(LauncherRow2Image, gtk4::Image);
widget!(LauncherRow2Label, gtk4::Label);
widget!(LauncherRow3, gtk4::Box);
widget!(LauncherRow3Image, gtk4::Image);
widget!(LauncherRow3Label, gtk4::Label);
widget!(LauncherRow4, gtk4::Box);
widget!(LauncherRow4Image, gtk4::Image);
widget!(LauncherRow4Label, gtk4::Label);
widget!(LauncherRow5, gtk4::Box);
widget!(LauncherRow5Image, gtk4::Image);
widget!(LauncherRow5Label, gtk4::Label);
widget!(HtopWindow, gtk4::Window);
widget!(WeatherWindow, gtk4::Window);
widget!(Hourly1, gtk4::Label);
widget!(Hourly2, gtk4::Label);
widget!(Hourly3, gtk4::Label);
widget!(Hourly4, gtk4::Label);
widget!(Hourly5, gtk4::Label);
widget!(Hourly6, gtk4::Label);
widget!(Hourly7, gtk4::Label);
widget!(Hourly8, gtk4::Label);
widget!(Hourly9, gtk4::Label);
widget!(Hourly10, gtk4::Label);
widget!(Daily1, gtk4::Label);
widget!(Daily2, gtk4::Label);
widget!(Daily3, gtk4::Label);
widget!(Daily4, gtk4::Label);
widget!(Daily5, gtk4::Label);
widget!(Daily6, gtk4::Label);

pub(crate) fn load_widgets(builder: &gtk4::Builder) {
    load_TopBarWindow(builder);
    load_WorkspacesWidgetButton1(builder);
    load_WorkspacesWidgetButton2(builder);
    load_WorkspacesWidgetButton3(builder);
    load_WorkspacesWidgetButton4(builder);
    load_WorkspacesWidgetButton5(builder);
    load_WorkspacesWidgetButton6(builder);
    load_WorkspacesWidgetButton7(builder);
    load_WorkspacesWidgetButton8(builder);
    load_WorkspacesWidgetButton9(builder);
    load_WorkspacesWidgetButton10(builder);
    load_HtopWidget(builder);
    load_WeatherWidget(builder);
    load_WeatherWidgetLabel(builder);
    load_LanguageWidgetLabel(builder);
    load_SoundWidgetImage(builder);
    load_SoundWidgetScale(builder);
    load_CPUWidgetLabel1(builder);
    load_CPUWidgetLabel2(builder);
    load_CPUWidgetLabel3(builder);
    load_CPUWidgetLabel4(builder);
    load_CPUWidgetLabel5(builder);
    load_CPUWidgetLabel6(builder);
    load_CPUWidgetLabel7(builder);
    load_CPUWidgetLabel8(builder);
    load_CPUWidgetLabel9(builder);
    load_CPUWidgetLabel10(builder);
    load_CPUWidgetLabel11(builder);
    load_CPUWidgetLabel12(builder);
    load_RAMWidget(builder);
    load_RAMWidgetLabel(builder);
    load_NetworkWidget(builder);
    load_NetworkWidgetLabel(builder);
    load_ClockWidgetLabel(builder);
    load_PowerWidget(builder);
    load_LogoutScreenWindow(builder);
    load_LogoutScreenLockButton(builder);
    load_LogoutScreenRebootButton(builder);
    load_LogoutScreenShutdownButton(builder);
    load_LogoutScreenLogoutButton(builder);
    load_NetworksWindow(builder);
    load_NetworkRow1(builder);
    load_NetworkRow2(builder);
    load_NetworkRow3(builder);
    load_NetworkRow4(builder);
    load_NetworkRow5(builder);
    load_NetworkSettingsRow(builder);
    load_NetworkExitRow(builder);
    load_LauncherWindow(builder);
    load_LauncherEntry(builder);
    load_LauncherRow1(builder);
    load_LauncherRow1Image(builder);
    load_LauncherRow1Label(builder);
    load_LauncherRow2(builder);
    load_LauncherRow2Image(builder);
    load_LauncherRow2Label(builder);
    load_LauncherRow3(builder);
    load_LauncherRow3Image(builder);
    load_LauncherRow3Label(builder);
    load_LauncherRow4(builder);
    load_LauncherRow4Image(builder);
    load_LauncherRow4Label(builder);
    load_LauncherRow5(builder);
    load_LauncherRow5Image(builder);
    load_LauncherRow5Label(builder);
    load_HtopWindow(builder);
    load_WeatherWindow(builder);
    load_Hourly1(builder);
    load_Hourly2(builder);
    load_Hourly3(builder);
    load_Hourly4(builder);
    load_Hourly5(builder);
    load_Hourly6(builder);
    load_Hourly7(builder);
    load_Hourly8(builder);
    load_Hourly9(builder);
    load_Hourly10(builder);
    load_Daily1(builder);
    load_Daily2(builder);
    load_Daily3(builder);
    load_Daily4(builder);
    load_Daily5(builder);
    load_Daily6(builder);
}
