[package]
name = "memory"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
pin-project-lite = { workspace = true }
