[package]
name = "layer-shell-io"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
paste = { workspace = true }
chrono = { workspace = true }

clap = { version = "4.5", default-features = false, features = [
    "std",
    "help",
    "derive",
    "suggestions",
] }
clap_complete = "4.5"
pretty_env_logger = "0.5"
dbus-tokio = "0.7"
dbus = "0.9"
layer-shell-dbus = { path = "../dbus" }
layer-shell-pipewire = { path = "../pipewire" }
layer-shell-hyprland = { path = "../hyprland" }
layer-shell-weather = { path = "../weather" }
