language = "C"

pragma_once = true
usize_is_size_t = true
style = "both"

includes = ["io/bindgen-fix.h"]

[parse]
parse_deps = true
include = [
    "clock",
    "control",
    "cpu",
    "ffi",
    "hyprland",
    "memory",
    "network",
    "sound",
    "tracker",
    "tray",
    "weather",
]

[export]
prefix = "IO_"
exclude = ["CArray_TrayItem"]
include = ["TrayItem"]

[enum]
prefix_with_name = true
