[package]
name = "network"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
zbus = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
futures = { workspace = true }
tokio-stream = { workspace = true }
utils = { path = "../utils" }
