/* automatically generated by rust-bindgen 0.72.1 */

pub(crate) const TLS1_2_VERSION: u32 = 771;
pub(crate) const SSL_VERIFY_PEER: u32 = 1;
pub(crate) const SSL_ERROR_WANT_READ: u32 = 2;
pub(crate) const SSL_ERROR_WANT_WRITE: u32 = 3;
pub(crate) const SSL_ERROR_ZERO_RETURN: u32 = 6;
pub(crate) type BIO = u8;
pub(crate) type X509_STORE_CTX = u8;
pub(crate) type X509_VERIFY_PARAM = u8;
pub(crate) type SSL = u8;
pub(crate) type SSL_CTX = u8;
pub(crate) type BIO_METHOD = u8;
unsafe extern "C" {
    pub(crate) fn BIO_new(type_: *const BIO_METHOD) -> *mut BIO;
}
unsafe extern "C" {
    pub(crate) fn BIO_read(
        b: *mut BIO,
        data: *mut ::core::ffi::c_void,
        dlen: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub(crate) fn BIO_write(
        b: *mut BIO,
        data: *const ::core::ffi::c_void,
        dlen: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub(crate) fn BIO_ctrl(
        bp: *mut BIO,
        cmd: ::core::ffi::c_int,
        larg: ::core::ffi::c_long,
        parg: *mut ::core::ffi::c_void,
    ) -> ::core::ffi::c_long;
}
unsafe extern "C" {
    pub(crate) fn BIO_s_mem() -> *const BIO_METHOD;
}
unsafe extern "C" {
    pub(crate) fn X509_VERIFY_PARAM_set1_host(
        param: *mut X509_VERIFY_PARAM,
        name: *const ::core::ffi::c_char,
        namelen: usize,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub(crate) fn X509_VERIFY_PARAM_set_hostflags(
        param: *mut X509_VERIFY_PARAM,
        flags: ::core::ffi::c_uint,
    );
}
pub(crate) type SSL_METHOD = u8;
pub(crate) type SSL_verify_cb = ::core::option::Option<
    unsafe extern "C" fn(
        preverify_ok: ::core::ffi::c_int,
        x509_ctx: *mut X509_STORE_CTX,
    ) -> ::core::ffi::c_int,
>;
unsafe extern "C" {
    pub(crate) fn SSL_CTX_new(meth: *const SSL_METHOD) -> *mut SSL_CTX;
}
unsafe extern "C" {
    pub(crate) fn SSL_CTX_free(arg1: *mut SSL_CTX);
}
unsafe extern "C" {
    pub(crate) fn SSL_set_bio(s: *mut SSL, rbio: *mut BIO, wbio: *mut BIO);
}
unsafe extern "C" {
    pub(crate) fn SSL_CTX_set_verify(ctx: *mut SSL_CTX, mode: ::core::ffi::c_int, callback: SSL_verify_cb);
}
unsafe extern "C" {
    pub(crate) fn SSL_new(ctx: *mut SSL_CTX) -> *mut SSL;
}
unsafe extern "C" {
    pub(crate) fn SSL_get0_param(ssl: *mut SSL) -> *mut X509_VERIFY_PARAM;
}
unsafe extern "C" {
    pub(crate) fn SSL_free(ssl: *mut SSL);
}
unsafe extern "C" {
    pub(crate) fn SSL_connect(ssl: *mut SSL) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub(crate) fn SSL_read(
        ssl: *mut SSL,
        buf: *mut ::core::ffi::c_void,
        num: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub(crate) fn SSL_write(
        ssl: *mut SSL,
        buf: *const ::core::ffi::c_void,
        num: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub(crate) fn SSL_get_error(s: *const SSL, ret_code: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub(crate) fn TLS_client_method() -> *const SSL_METHOD;
}
unsafe extern "C" {
    pub(crate) fn SSL_set_connect_state(s: *mut SSL);
}
unsafe extern "C" {
    pub(crate) fn SSL_CTX_set_default_verify_paths(ctx: *mut SSL_CTX) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub(crate) fn __openssl_SSL_CTX_set_min_proto_version(
        ctx: *mut SSL_CTX,
        version: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub(crate) fn __openssl_SSL_set_tlsext_host_name(
        ssl: *mut SSL,
        name: *mut ::core::ffi::c_char,
    ) -> ::core::ffi::c_long;
}
