[package]
name = "control"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
zbus = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
tokio-util = { workspace = true }
futures = { workspace = true }
pin-project-lite = { workspace = true }
