[package]
name = "clock"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
futures-util = { workspace = true }
pin-project-lite = { workspace = true }
chrono = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }

utils = { path = "../utils" }
