[package]
name = "clock"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
pin-project-lite = { workspace = true }
